declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly Contact: 'Contact';
  readonly Contact_contactContainer: 'Contact_contactContainer';
  readonly Contact_section: 'Contact_section';
  readonly Contact_textContainer: 'Contact_textContainer';
  readonly Contact_text: 'Contact_text';
  readonly Contact_content: 'Contact_content';
  readonly Contact_svgContainer: 'Contact_svgContainer';
};
export = classNames;
