declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly ImageComparator: 'ImageComparator';
  readonly ImageComparator_imageComparer: 'ImageComparator_imageComparer';
  readonly ImageComparator_circle: 'ImageComparator_circle';
  readonly ImageComparator_line: 'ImageComparator_line';
  readonly ImageComparator_backImage: 'ImageComparator_backImage';
};
export = classNames;
