declare const classNames: {
  readonly Intro: 'Intro';
  readonly '875rem': '875rem';
  readonly Intro_myIntroduction: 'Intro_myIntroduction';
  readonly Intro_introTextContainer: 'Intro_introTextContainer';
  readonly Intro_text: 'Intro_text';
  readonly Intro_strong: 'Intro_strong';
  readonly Intro_line1: 'Intro_line1';
  readonly Intro_line2: 'Intro_line2';
  readonly Intro_ilustration: 'Intro_ilustration';
  readonly Intro_design: 'Intro_design';
  readonly Intro_textDescription: 'Intro_textDescription';
  readonly ImageComparator: 'ImageComparator';
  readonly ImageComparator_imageComparer: 'ImageComparator_imageComparer';
  readonly ImageComparator_circle: 'ImageComparator_circle';
  readonly ImageComparator_line: 'ImageComparator_line';
  readonly ImageComparator_backImage: 'ImageComparator_backImage';
  readonly ImageComparator_galleryImage: 'ImageComparator_galleryImage';
  readonly Intro_em: 'Intro_em';
  readonly Intro_lines: 'Intro_lines';
  readonly Intro_ilustrationImage: 'Intro_ilustrationImage';
  readonly Intro_svg: 'Intro_svg';
  readonly Intro_neomorphicSVG: 'Intro_neomorphicSVG';
  readonly ImageComparator_gallery: 'ImageComparator_gallery';
  readonly ImageComparator_dragger: 'ImageComparator_dragger';
  readonly ImageComparator_clipped: 'ImageComparator_clipped';
};
export = classNames;
