declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly LanguageSwitcher: 'LanguageSwitcher';
  readonly '875rem': '875rem';
  readonly LanguageSwitcher_buttons: 'LanguageSwitcher_buttons';
  readonly LanguageSwitcher_esButton: 'LanguageSwitcher_esButton';
  readonly LanguageSwitcher_esButtonText: 'LanguageSwitcher_esButtonText';
  readonly LanguageSwitcher_enButton: 'LanguageSwitcher_enButton';
  readonly LanguageSwitcher_enButtonText: 'LanguageSwitcher_enButtonText';
};
export = classNames;
