declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly Input: 'Input';
  readonly NeuTooltipTool_row: 'NeuTooltipTool_row';
  readonly NeuTooltipTool_labelContainer: 'NeuTooltipTool_labelContainer';
  readonly NeuTooltipTool_label: 'NeuTooltipTool_label';
  readonly Configuration: 'Configuration';
  readonly Configuration_copy: 'Configuration_copy';
};
export = classNames;
