declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly ContactInformation: 'ContactInformation';
  readonly ContactInformation_text: 'ContactInformation_text';
  readonly ContactInformation_numberContainer: 'ContactInformation_numberContainer';
  readonly ContactInformation_number: 'ContactInformation_number';
  readonly ContactInformation_socialIconContainer: 'ContactInformation_socialIconContainer';
  readonly ContactInformation_span: 'ContactInformation_span';
};
export = classNames;
