declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly Form: 'Form';
  readonly Form_button: 'Form_button';
  readonly Form_buttonText: 'Form_buttonText';
  readonly Form_textarea: 'Form_textarea';
};
export = classNames;
