declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly Illustration: 'Illustration';
  readonly Illustration_svgContainer: 'Illustration_svgContainer';
  readonly Illustration_svg: 'Illustration_svg';
  readonly Illustration_contactButton: 'Illustration_contactButton';
  readonly Illustration_contactButtonText: 'Illustration_contactButtonText';
};
export = classNames;
