declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly SkillBox: 'SkillBox';
  readonly SkillBox_section: 'SkillBox_section';
  readonly SkillBox_titleContainer: 'SkillBox_titleContainer';
  readonly SkillBox_title: 'SkillBox_title';
  readonly SkillBox_skillsInputs: 'SkillBox_skillsInputs';
};
export = classNames;
