declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly Abilities: 'Abilities';
  readonly Abilities_svgContainer: 'Abilities_svgContainer';
  readonly Abilities_text: 'Abilities_text';
  readonly Abilities_text___rotated: 'Abilities_text___rotated';
};
export = classNames;
