declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly ThemeColorSwitcher: 'ThemeColorSwitcher';
  readonly ThemeColorSwitcher_text: 'ThemeColorSwitcher_text';
  readonly ThemeColorSwitcher_toggle: 'ThemeColorSwitcher_toggle';
  readonly ThemeColorSwitcher_toggleSwitch: 'ThemeColorSwitcher_toggleSwitch';
  readonly ThemeColorSwitcher_toggleCheckbox: 'ThemeColorSwitcher_toggleCheckbox';
};
export = classNames;
