declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly Skill: 'Skill';
  readonly Skill_skillText: 'Skill_skillText';
  readonly Skill_chargeBarContainer: 'Skill_chargeBarContainer';
  readonly Skill_chargeBar: 'Skill_chargeBar';
  readonly Skill_nullPart: 'Skill_nullPart';
  readonly Skill_circleContainer: 'Skill_circleContainer';
  readonly Skill_neonPart: 'Skill_neonPart';
};
export = classNames;
