declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly Navbar: 'Navbar';
  readonly '875rem': '875rem';
  readonly Navbar_logo: 'Navbar_logo';
  readonly Navbar_bottomNeon: 'Navbar_bottomNeon';
  readonly Navbar_menuToggle: 'Navbar_menuToggle';
  readonly Navbar_button: 'Navbar_button';
  readonly Navbar_hamburger: 'Navbar_hamburger';
};
export = classNames;
