declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly Intro: 'Intro';
  readonly Intro_myIntroduction: 'Intro_myIntroduction';
  readonly Intro_text: 'Intro_text';
  readonly Intro_strong: 'Intro_strong';
  readonly Intro_em: 'Intro_em';
  readonly Intro_lines: 'Intro_lines';
  readonly Intro_line1: 'Intro_line1';
  readonly Intro_line2: 'Intro_line2';
  readonly Intro_ilustration: 'Intro_ilustration';
  readonly Intro_ilustrationImage: 'Intro_ilustrationImage';
  readonly Intro_design: 'Intro_design';
};
export = classNames;
