declare const classNames: {
  readonly container: 'container';
  readonly panel: 'panel';
  readonly componente: 'componente';
  readonly gallery: 'gallery';
  readonly dragger: 'dragger';
  readonly clipped: 'clipped';
  readonly containers: 'containers';
  readonly blue: 'blue';
  readonly orange: 'orange';
  readonly purple: 'purple';
  readonly red: 'red';
  readonly green: 'green';
  readonly gray: 'gray';
  readonly Arrow: 'Arrow';
  readonly active: 'active';
  readonly LightSourceSelector: 'LightSourceSelector';
  readonly LightSourceSelector_disabled: 'LightSourceSelector_disabled';
};
export = classNames;
